name: base_doanh
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Dart
  dartx: ^1.1.0
  auto_size_text: ^3.0.0
  intl_utils: ^2.8.1
  optimized_cached_image: ^3.0.1

  #Favourite library
  provider: ^6.0.5
  flutter_bloc: ^8.1.1
  google_fonts: ^4.0.3
  url_launcher: ^6.1.8
  path_provider: ^2.0.12
  webview_flutter: ^4.0.2
  shared_preferences: ^2.0.17
  font_awesome_flutter: ^10.3.0
  lint: ^2.0.1
  image_picker: ^0.8.6+1

  #Library helpful
  intl: ^0.17.0
  event_bus: ^2.0.0
  equatable: ^2.0.5
  fluttertoast: ^8.1.2
  retrofit: ^3.3.1
  json_annotation: ^4.8.0
  flutter_screenutil: ^5.6.1
  cached_network_image: ^3.2.3
  smooth_page_indicator: ^1.0.0+2
  flutter_staggered_grid_view: ^0.6.2
  logger: ^1.1.0
  rxdart: ^0.27.7
  expandable: ^5.0.1
  sliding_up_panel: ^2.0.0+1
  qr_code_scanner: ^1.0.1

  carousel_slider: ^4.2.1
  dots_indicator: ^2.1.0
  #svg
  flutter_svg: ^2.0.0+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  dart_ipify: ^1.1.1
  crypto: ^3.0.2

  # GETX
  get: ^4.6.5
  pretty_dio_logger: ^1.1.1

  injectable: ^2.1.0
  freezed: ^2.3.2
  tuple: ^2.0.1
  analyzer: ^5.4.0
  flutter_share: ^2.0.0
  connectivity_plus: ^3.0.2
  keyboard_dismisser: ^3.0.0
  pin_code_fields: ^7.4.0
  qr_flutter: ^4.0.0
  permission_handler: ^10.2.0
  image_gallery_saver: ^1.7.1
  expandable_page_view: ^1.0.17


  #login social
  google_sign_in: ^5.4.4
  flutter_facebook_auth: ^5.0.7
  sign_in_with_apple: ^4.3.0
  local_auth: ^2.1.3
  queue: ^3.1.0+2

  #image picker:
  file_picker: ^5.2.5
  device_info_plus: ^8.0.0
  flutter_slidable: ^2.0.0
  flutter_native_image: ^0.0.6+1
  syncfusion_flutter_datepicker: ^20.4.48

  syncfusion_flutter_gauges: ^20.4.48
  confetti: ^0.7.0
  firebase_messaging: ^14.2.1
  firebase_core: ^2.4.1
  flutter_local_notifications: ^13.0.0
  share_plus: ^6.3.0
  just_audio: ^0.9.31

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner:  #flutter pub run build_runner build --delete-conflicting-outputs
  json_serializable: ^6.6.1
  injectable_generator: ^2.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SFUIText
      fonts:
        - asset: assets/fonts/SFUIText-Bold.ttf
        - asset: assets/fonts/SFUIText-Regular.ttf
        - asset: assets/fonts/SFUIText-SemiBold.ttf
        - asset: assets/fonts/SFUIText-Medium.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true